config/routes.rb
Rails.application.routes.draw do
  resources :books

  devise_for :users
  get 'pages/home'

    root 'pages#home'

end

app/models/book.rb
class Book < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!, only: [:new,:edit,:create,:update,:destroy]
    before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
      @books = Book.where(availability: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
      @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
      if current_user
          redirect_to books_path
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
        <%= link_to book_path(book) do%>
        <%= image_tag "adwr4.jpg", class:"img-responsive" %>
        <% end%>
        <div class="caption">
           
            <p><%= link_to book_path(book) do%><strong><%= book.name %></strong> <%end%></p>
            
            <p>$<%= book.price.to_f/100 %></p>
        </div>
    </a>
  </div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: {class:"form-signin"}) do |f| %>
  <%= f.error_notification %>

  
<%= f.input :name, required: true, label: false, placeholder: "Name", input_html: {class: "form-control"} %>
<%= f.input :author, required: true, label: false, placeholder: "Author's Name", input_html: {class: "form-control"} %>
<%= f.input :description , required: true, label: false, placeholder: "Description", input_html: {class: "form-control", rows: 5}%>
<%= f.input :price, required: true, label: false, placeholder: "Price", input_html: {class: "form-control"} %>
<div class="checkbox">
    <%= f.input :availability, required: true %>
</div>
  
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
 
<% end %>

app/views/books/edit.html.erb
<h1 class="text-center">Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="row">
    <%= render @books %>
</div>

app/views/books/new.html.erb
<h1 class="text-center">New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="container">
<div class="row">
 
<div class="col-md-6">
<%= image_tag "adwr4.jpg", class:"img-responsive" %>
</div>

<div class="col-md-6">
<h3><%= @book.name %> by <%= @book.author %></h3>
<p class="justify"><%= @book.description %></p>
<h4 class="text-right">$<%= @book.price.to_f / 100 %></h4>
</div>
 
</div>
</div>
 
<%= link_to "Edit", edit_book_path(@book)  %>
<%= link_to "Back", books_path  %>
<!--
<p>
  <strong>Availability:</strong>
  <%= @book.availability %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>-->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
        <%= link_to "eStuk", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Books", books_path %></li>
          <% if current_user %>
      
      <li><%= link_to "Settings", edit_user_registration_path %></li>
     
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
      
      <% else %>
      
        <li><%= link_to "Login", new_user_session_path %></li>
      
      <% end %>  
      </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Estuk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render "layouts/header" %>
    <div class="container">
        
        <%= yield %>
        
    </div>


</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
<h1>Welcome to our store</h1>
<p>The largest online Digital Books Store</p>
<%= link_to "Books", books_path, class: "btn btn-primary btn-lg" %>
    <% if !current_user %>
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    <%end%>
</div>